### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by thmo** [lxc/lua-lxc#1]
Now that LXC 3.0.0 has been released without Lua bindings, it would be nice (from a downstream Fedora packager's point of view) to have a released version of the Lua bindings.

**Comment by thmo** [comment]
Oh, and btw, please give it a release number >= 3, so that a proper upgrade path can be easily maintained.

**Comment by brauner** [comment]
Hm, not sure if we're going to do 3.0.0 here? @stgraber?

**Comment by stgraber** [comment]
Done. Tagged and there are release tarballs up on the website. Completely untested though, would love to have someone step up to maintain this binding...
